---
title: "Homework #6"
author: "Sophia Miller"
date: "11/21/2019"
output: github_document
---

```{r setup}
library(tidyverse)
```

# Problem 1

Importing and tidying the birthweight dataset:

```{r birthweight_data}
birthweight_data = read_csv(file = "./data/birthweight.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    babysex = as.factor(babysex),
    frace = as.factor(frace),
    malform = as.factor(malform),
    mrace = as.factor(mrace),
  ) %>% 
  mutate(
    babysex = fct_infreq(babysex),
    frace = fct_infreq(frace),
    malform = fct_infreq(malform),
    mrace = fct_infreq(mrace))
```

Test variables in separate models individually to assess significance:

```{r}
fit_fincome = lm(bwt ~ fincome, data = birthweight_data) 

fit_gaweeks = lm(bwt ~ gaweeks, data = birthweight_data)

fit_malform = lm(bwt ~ malform, data = birthweight_data)

fit_menarche = lm(bwt ~ menarche, data = birthweight_data)

fit_momage = lm(bwt ~ momage, data = birthweight_data)

fit_mrace = lm(bwt ~ mrace, data = birthweight_data)

fit_ppbmi = lm(bwt ~ ppbmi, data = birthweight_data)

fit_smoken = lm(bwt ~ smoken, data = birthweight_data) 

fit_fincome %>%
  broom::tidy()

fit_gaweeks %>%
  broom::tidy()

fit_malform %>%
  broom::tidy()

fit_menarche %>%
  broom::tidy()

fit_momage %>%
  broom::tidy()

fit_mrace %>%
  broom::tidy()

fit_ppbmi %>%
  broom::tidy()

fit_smoken %>%
  broom::tidy()
```

Multivariable model with variabesl that were significant:

```{r}
#fincome, gaweeks, momage, mrace, ppbmi, smoken
fit_multi = lm(bwt ~ fincome + gaweeks + momage + mrace + ppbmi + smoken, data = birthweight_data) 

fit_multi %>% 
  broom::tidy()

#gaweeks, mrace, ppbmi, smoken
fit_final = lm(bwt ~ gaweeks + mrace + ppbmi + smoken, data = birthweight_data)
fit_final %>% 
  broom::tidy()
```

